### ISSUE TITLE
Runtime error with positional arguments after mode

### ISSUE THREAD

**Issue by marekmaskarinec** [skejeton/umka-args#3]
I found an issue where if a mode has positional arguments, providing an optional one will cause a runtime error. For example, try `umbox init --help`.

**Comment by ske2004** [comment]
Strange, I thought I fixed this bug in https://github.com/skejeton/umka-args/commit/3a0f1707591b641a103ce46f1d985657fda88a80, do you have an outdated version of args.um in umbox? The command works just fine for me. A stack trace would be helpful.
![image](https://github.com/user-attachments/assets/09005fd2-24ff-42d0-9be7-57b40c3e4d04)

**Comment by marekmaskarinec** [comment]
Yes, my local copy of args.um is outdated. Sorry for bothering.

**Comment by ske2004** [comment]
Don't worry, it happens =)
